### Add product to catalog

POST https://localhost/products
Content-Type: application/x-www-form-urlencoded

name=Example product 2&price=1200

### Update product

PATCH https://localhost/products/2234d96c-ef71-4f94-a02a-2e513ddfc469/update
Content-Type: application/x-www-form-urlencoded

name=Example product&price=13003

### Remove product from catalog

DELETE https://localhost/products/ec0c615d-0571-4e4b-9582-59a7edaf8117

### List products

GET https://localhost/products

### Create cart

POST https://localhost/cart

> {% client.global.set("cart_id", response.body.cart_id) %}

### Add product to cart

PUT https://localhost/cart/{{cart_id}}/545ca524-ea28-4cf7-9f97-fb53452cf3b7
Content-Type: application/x-www-form-urlencoded

amount=1

### Remove product from cart

DELETE https://localhost/cart/{{cart_id}}/119435f1-b1e7-43bd-9d87-5f06f32da67f
Content-Type: application/x-www-form-urlencoded

amount=1

### Show cart

GET https://localhost/cart/{{cart_id}}